Project: Advanced Building Blocks - Bubble Sort
ozovalihasan/bubble-sort pull request #1
Opened 2020-05-13 13:42 UTC by ozovalihasan

Project is done by following the instructions:

- bubble_sort and bubble_sort_by are used as method. bubble_sort is used to sort integers and bubble_sort_by for arrays containing integers
- It is checked by using rubocop

2020-05-13 23:27 UTC, mikenath223 requested changes
Hi Team 👋

You  seem to have done quite well on this @ozovalihasan  and @Daniduran-dev  👍

- [ ] - However, on testing out your code, it seems to fail at every point. Kindly rework it again, and make sure it passes with some examples before requesting another review.

Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-05-14 08:31 UTC, ozovalihasan commented
- Problem is solved 
- One more optimization is added for both methods
- Fix all errors found by rubocop

2020-05-15 01:01 UTC, euqueme requested changes
> ### Pull request under the review by Maria Eugenia Queme P. (TSE)

### Hello @ozovalihasan and @Daniduran-dev  :balloon: :lollipop: 

### Thank you for doing the changes requested by the previous reviewer, your code is working just fine and you've used ruby convention very well so congratulations you may merge this branch :tada: :tada: :tada: 

#### Consideration:

- [ ] This is a collaborative project so there should be an even number of commit messages from both students, take this into account for future projects.

### Keep up the good work :clinking_glasses: 

PROJECT STATUS: APPROVED :green_apple:

2020-05-15 01:01 UTC, euqueme commented on README.md
> +👤 **Hasan Özovalı**
- [x] Change this name to Daniel Duran before you merge

2020-05-15 08:20 UTC, ozovalihasan commented
Thanks for your feedback, @euqueme. I fixed the author's names. We will balance the number of commits done by each one for future projects

2020-05-15 08:20 UTC, merged